name 'chef-mre'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chef-mre'
long_description 'Installs/Configures chef-mre'
version '0.1.0'
