name 'chef-mre'
maintainer 'Galen Emery'
maintainer_email 'galen.emery@gmail.com'
license 'apache2'
description 'Installs/Configures chef-mre'
long_description 'Installs/Configures chef-mre'
version '0.1.0'

depends 'chef-ingredient', '>= 0.18.5'
depends 'hostsfile'
depends 'line'